# Array Creating

In [1]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [2]:
a = [1,2,3,4,5]
print(a)

[1, 2, 3, 4, 5]


In [4]:
n = [2,4,6]
m = [8,10,6]
print(n+m)

[2, 4, 6, 8, 10, 6]


In [6]:
n = [2,4,6]
m = [8,10,6]
res=[]
for i in range(len(n)):
    res.append(n[i]+m[i])
print(res)

[10, 14, 12]


In [9]:
import numpy as np
a = np.array([1,2,3])
b = np.array([4,5,6])
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [16]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
ar = np.array([[1,2,3],[4,5,6]])
a = np.array([[[1,2],
               [3,4],
               [5,6]]])
print(arr)
print(ar)
print(a)
print(ar.shape)
print(arr.ndim)
print(ar.ndim)
print(a.ndim)
print(arr.size)
print(ar.size)
print(a.size)
print(a.dtype)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
[[[1 2]
  [3 4]
  [5 6]]]
(2, 3)
1
2
3
5
6
6
int64


In [26]:
import numpy as np
a = np.array([1,2,3,4,5])
b = np.zeros(5)
print(a)
print(b)
c = np.array((2,2))
print(c)
d = np.ones(3)
print(d)
e = np.ones((2,3))
print(e)

[1 2 3 4 5]
[0. 0. 0. 0. 0.]
[2 2]
[1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]]


In [28]:
import numpy as np
a = np.array([1,2,3,4,5])
b = np.zeros(5)
print(a)
print(b)
c = np.arange(1000)
print(np.arange(1,10,2))
print(np.linspace(0,20,5))
print(np.random.rand(5))
print(np.random.randint(1,100,7))
print(np.random.randn(5

[1 2 3 4 5]
[0. 0. 0. 0. 0.]
[1 3 5 7 9]
[ 0.  5. 10. 15. 20.]
[3.80700300e-01 6.73837997e-01 9.82407390e-01 5.53414756e-04
 9.27594501e-01]
[81 14 80 71 44  9 25]
[ 2.1533537   1.32944405 -0.17947289 -0.72220331  0.16564269]


# Indexing and Slicing

In [49]:
import numpy as np
# 1D array indexing
a = np.array([10,20,30,40,50,60,70])
print(a[2])
print(a[-7])
# 2D array indexing
b = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
print(b[1][1])
# 1D Slicing
print(a[2:7])
print(a[:4])
print(a[::2])
# 2D Slicing
print(b[1])
print(b[:,1])
print(a[a>50])
print(a[a<50])
print(a[[0,4,3,6]])
print(a[a % 2 == 0])
a[4] = 1000
print(a)

30
10
5
[30 40 50 60 70]
[10 20 30 40]
[10 30 50 70]
[4 5 6]
[2 5 8]
[60 70]
[10 20 30 40]
[10 50 40 70]
[10 20 30 40 50 60 70]
[  10   20   30   40 1000   60   70]


## Mathematical operation in numpy

In [52]:
import numpy as np
a = np.array([1,2,3])
print(a + 10)
b = np.array([[1,2,3],
              [4,5,6]])
print(b + 10)
print(a + b) #number of columns must be same

[11 12 13]
[[11 12 13]
 [14 15 16]]
[[2 4 6]
 [5 7 9]]


## Matrix Operation

In [59]:
import numpy as np
a = np.array([[1,2],
            [3,4]])
b = np.array([[4,3],
             [2,1]])
print(a * b)
print(np.dot(a,b))
print(a @ b)
print(np.matmul(a,b))
print(a.T) #row becomes column and column becomes row.

[[4 6]
 [6 4]]
[[ 8  5]
 [20 13]]
[[ 8  5]
 [20 13]]
[[ 8  5]
 [20 13]]
[[1 3]
 [2 4]]


In [62]:
# Universal mathematical function
import numpy as np
a = np.array([4,9,16])
print(np.sqrt(a))
b = np.array([-5,-6,-2,-8])
print(np.abs(b))
print(np.log(a))
print(np.exp(a))

[2. 3. 4.]
[5 6 2 8]
[1.38629436 2.19722458 2.77258872]
[5.45981500e+01 8.10308393e+03 8.88611052e+06]


In [64]:
# Round Function
arr = np.array([1.234,5.678])
print(np.round(arr,2))
print(np.floor(arr))
print(np.ceil(arr))

[1.23 5.68]
[1. 5.]
[2. 6.]


In [80]:
# Statistical function
import numpy as np
a = np.array([10,2,3,40,50])
print(np.mean(a))
print(np.median(a))
print(np.std(a))
print(np.max(a))
print(np.min(a))
print(np.percentile(a,75))
print(np.percentile(a,100))
print(np.var(a))
print(np.argmin(a))
print(np.argmax(a))
b = np.array([1,2,3,4,5])
c = np.array([10,8,6,4,2])
print(np.corrcoef(b,c))
d = np.array([1,2,3,4,5])
e = np.array([2,4,6,8,10])
print(np.corrcoef(d,e))

21.0
10.0
20.039960079800558
50
2
40.0
50.0
401.6
1
4
[[ 1. -1.]
 [-1.  1.]]
[[1. 1.]
 [1. 1.]]


In [84]:
# Aggrigate Function
a = np.array([[1,2,3],
             [4,5,6]])
print(np.sum(a))
print(np.sum(a,axis = 1))
print(np.sum(a,axis = 0))

21
[ 6 15]
[5 7 9]


# TASK

In [98]:
import numpy as np
scores = np.array([[70,80,92],
                   [80,89,92],
                   [62,79,92]])
average = np.mean(scores)
print("Average Score: ",average)
high = np.sum(scores,axis = 1)
print(high)
min = np.min(high)
print(min)
max = np.max(high)
print(max)
total = np.sum(scores)
normalization = (scores - scores.min())/scores.max() - scores.min()
print(normalization)
subject = np.mean(scores,axis = 0)
print(subject)

Average Score:  81.77777777777777
[242 261 233]
233
261
[[-61.91304348 -61.80434783 -61.67391304]
 [-61.80434783 -61.70652174 -61.67391304]
 [-62.         -61.81521739 -61.67391304]]
[70.66666667 82.66666667 92.        ]
